More post-merge cleanup from upstream: do not use EmojiText anymore, it has been removed upstream. Also was causing very weird errors "TypeError: (0,a.mightContainEmoji) is not a function"... solved by removing it :)